# Generated by Django 6.0.4 on 2026-04-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_alter_actividad_f_completada_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='plan',
            field=models.CharField(choices=[('basico', 'Básico'), ('premium', 'Premium'), ('vip', 'VIP')], default='basico', max_length=10),
        ),
    ]
